DELIMITER $$

USE `igreja`$$

DROP PROCEDURE IF EXISTS `membro_insere`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `membro_insere`(
	vfrequencia 						INT(11),
  vnome 									VARCHAR(100),
  vsexo 									CHAR(1),
  vdatanascimento 				DATE,
  vnaturalidade 					VARCHAR(100),
  vestado_id 							INT(11) UNSIGNED,
  vestadocivil 						INT(11) UNSIGNED,
  vlatitude 							VARCHAR(50),
  vlongitude 							VARCHAR(50),
  vrg 										VARCHAR(20),
  vorgao_emissor 					VARCHAR(20),
  vdata_expedicao 				DATE,
  vcpf 										VARCHAR(20),
  vemail 									VARCHAR(150),
  vfone 									VARCHAR(20),
  vcel 										VARCHAR(20),
  vescolaridade_id 				INT(11) UNSIGNED,
  vprofissao_id 					INT(11) UNSIGNED,
  vempresa 								VARCHAR(150),
  vdatabatismo 						DATE,
  vigrejabatismo 					VARCHAR(30),
  vpastorbatismo 					VARCHAR(20),
  vultimaigreja 					VARCHAR(30),
  vdatamembro 						DATE,
  vcargo_id 							INT(11) UNSIGNED,
  vempresa_id 						INT(11),
  venderecos_id						INT(11) UNSIGNED,
  venderecos_numero				VARCHAR(45),
  venderecos_complemento	VARCHAR(256),
  vuser_id 								INT(11),
  vcreated 								DATETIME,
  vmodified 							DATETIME,
  vtipo 									CHAR(1),
	vdata_casamento					DATE,
	vlocal_id								INT(11) UNSIGNED,
	vata_batismo						INT(11) UNSIGNED
)
BEGIN
	INSERT INTO membros
	(frequencia_id,
	 nome,
	 sexo,
	 datanascimento,
	 naturalidade,
	 estado_id,
	 estadocivil,
	 data_casamento,
	 latitude,
	 longitude,
	 rg,
	 orgao_emissor,
   data_expedicao,
	 cpf,
	 email,
	 fone,
	 cel,
	 escolaridade_id,
	 profissao_id,
	 empresa,
	 databatismo,
	 igrejas_id,
	 pastorbatismo,
	 ultimaigreja,
	 datamembro,
	 cargo_id,
	 empresa_id,
	 enderecos_id,
	 enderecos_numero,
	 enderecos_complemento,
	 user_id,
	 created,
	 modified,
	 tipo,
	 local_id,
	 ata_batismo)
	VALUES
	(vfrequencia,
	 vnome,
	 vsexo,
	 vdatanascimento,
	 vnaturalidade,
	 vestado_id,
	 vestadocivil,
	 vdata_casamento,
	 vlatitude,
	 vlongitude,
	 vrg,
	 vorgao_emissor,
   vdata_expedicao,
	 vcpf,
	 vemail,
	 vfone,
	 vcel,
	 vescolaridade_id,
	 vprofissao_id,
	 vempresa,
	 vdatabatismo,
	 vigrejabatismo,
	 vpastorbatismo,
	 vultimaigreja,
	 vdatamembro,
	 vcargo_id,
	 vempresa_id,
	 venderecos_id,
	 venderecos_numero,
	 venderecos_complemento,
	 vuser_id,
	 vcreated,
	 vmodified,
	 vtipo,
	 vlocal_id,
	 vata_batismo);
	SELECT LAST_INSERT_ID() id;
END$$

DELIMITER ;