/*
SQLyog Ultimate v12.4.3 (64 bit)
MySQL - 5.7.21 : Database - igreja
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

USE `igreja`;

/*Table structure for table `log_procs` */

DROP TABLE IF EXISTS `log_procs`;

CREATE TABLE `log_procs` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `proc` VARCHAR(300) COLLATE utf8_unicode_ci NOT NULL,
  `erro` SMALLINT(6) NOT NULL,
  `mensagem` TEXT COLLATE utf8_unicode_ci,
  `empresa_id` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
